### ISSUE TITLE
Updating removes existing token hotbars [BUG]

### ISSUE THREAD

**Issue by Arkandos** [p4535992/foundryvtt-token-hotbar#1]
**Module Version:** v1.4.9

**Describe the bug**

**Expected behavior**
Existing hotbars would remain

**Browser:**
 - Chrome

**Foundry Version:** v10.291

**Game System:** Custom System Builder

**Comment by kenderbard** [comment]
Is there any way this could possibly be restored? I set up about 20 different sheets worth of hotbars not that long ago.

**Comment by p4535992** [comment]
"not that long ago." did you mean on a foundryvtt 9 world right  ?

**Comment by Arkandos** [comment]
I can't speak for kenderbard, but both my versions were on v10. After switching to your repository, all hotbars disappeared.

**Comment by p4535992** [comment]
As the channel says it is a "hope and dream" on my part. Believe it or not
one group out of two (all of the same nationality) that I met never agreed
because some even though citizens (forgive the term) of a metric country
were used to the resources and documentation with imperial distance that
they found on the internet.

Il giorno lun 20 feb 2023 alle ore 13:41 Arkandos ***@***.***>
ha scritto:

**Comment by kenderbard** [comment]
Yes, same as Arkandos.
